- hosts: localhost
  vars_files:
     - secure.yml
  tasks:
  - name: ec2 launching 
    ec2:
       key_name: "t1key"
       instance_type: t2.micro
       image: "ami-0ebc1ac48dfd14136"
       wait: yes
       count: 1
       instance_tags:
               Name: soham
       vpc_subnet_id: "subnet-00f1e9cec1f388138"
       assign_public_ip: yes
       region: "ap-south-1"
       state: present
       group_id: "sg-0a2b1fc920523d922"
       aws_access_key: "{{ access }}" 
       aws_secret_key: "{{ secret }}"
      

